remote_theme: wu-kan
defaults:
  -
    scope:
      path: ""
      type: "patterns"
    values:
      layout: "pattern"
collections:
  patterns:
    output: true
    permalink: /:categories/:name
    layout: "pattern"
